version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test@123
      - POSTGRES_DB=testingdb
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test@123
      POSTGRES_DB: testingdb
    ports:
      - "5432:5432"
